#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'XQGrandPopupViewDemo' do

#pod 'XQGrandPopupView', '~> 1.0.0'
pod 'XQGrandPopupView', :path => '../'
pod 'SnapKit', '~> 5.0.0'

end
